version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=meu_usuario
      - POSTGRES_PASSWORD=minha_senha_super_segura
      - POSTGRES_DB=gastos_db
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data